spring:
  security:
    oauth2:
      client:
        registration:
          epicfhir:
            client-id: test-client-id
            client-secret: test-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          epicfhir:
            authorization-uri: http://localhost:${wiremock.server.port}/oauth2/authorize
            token-uri: http://localhost:${wiremock.server.port}/oauth2/token
            user-info-uri: http://localhost:${wiremock.server.port}/userinfo
            user-name-attribute: sub
